version: '3.8'

services:
  app:
    image: 'luan/product-quarkus:1.0-SNAPSHOT'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://db:5432/productdb
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
      QUARKUS_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - quarkus

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge
    name: quarkus